//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAutomex.HomeAutomexService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HomeAutomexService.HomeAutomexWSSoap")]
    public interface HomeAutomexWSSoap {
        
        // CODEGEN: Generating message contract since element name jUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirUsuário", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.InserirUsuárioResponse InserirUsuário(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirUsuário", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> InserirUsuárioAsync(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirUsuárioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirUsuário", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody Body;
        
        public InserirUsuárioRequest() {
        }
        
        public InserirUsuárioRequest(HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirUsuárioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jUsuario;
        
        public InserirUsuárioRequestBody() {
        }
        
        public InserirUsuárioRequestBody(string jUsuario) {
            this.jUsuario = jUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirUsuárioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirUsuárioResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirUsuárioResponseBody Body;
        
        public InserirUsuárioResponse() {
        }
        
        public InserirUsuárioResponse(HomeAutomex.HomeAutomexService.InserirUsuárioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirUsuárioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InserirUsuárioResult;
        
        public InserirUsuárioResponseBody() {
        }
        
        public InserirUsuárioResponseBody(string InserirUsuárioResult) {
            this.InserirUsuárioResult = InserirUsuárioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HomeAutomexWSSoapChannel : HomeAutomex.HomeAutomexService.HomeAutomexWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HomeAutomexWSSoapClient : System.ServiceModel.ClientBase<HomeAutomex.HomeAutomexService.HomeAutomexWSSoap>, HomeAutomex.HomeAutomexService.HomeAutomexWSSoap {
        
        public HomeAutomexWSSoapClient() {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeAutomexWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.InserirUsuárioResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirUsuário(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request) {
            return base.Channel.InserirUsuário(request);
        }
        
        public string InserirUsuário(string jUsuario) {
            HomeAutomex.HomeAutomexService.InserirUsuárioRequest inValue = new HomeAutomex.HomeAutomexService.InserirUsuárioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            HomeAutomex.HomeAutomexService.InserirUsuárioResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirUsuário(inValue);
            return retVal.Body.InserirUsuárioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirUsuárioAsync(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request) {
            return base.Channel.InserirUsuárioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> InserirUsuárioAsync(string jUsuario) {
            HomeAutomex.HomeAutomexService.InserirUsuárioRequest inValue = new HomeAutomex.HomeAutomexService.InserirUsuárioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirUsuárioAsync(inValue);
        }
    }
}
