//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAutomex.HomeAutomexService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HomeAutomexService.HomeAutomexWSSoap")]
    public interface HomeAutomexWSSoap {
        
        // CODEGEN: Generating message contract since element name jUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirUsuário", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.InserirUsuárioResponse InserirUsuário(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirUsuário", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> InserirUsuárioAsync(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request);
        
        // CODEGEN: Generating message contract since element name jResidencia from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirResidencia", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.InserirResidenciaResponse InserirResidencia(HomeAutomex.HomeAutomexService.InserirResidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirResidencia", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirResidenciaResponse> InserirResidenciaAsync(HomeAutomex.HomeAutomexService.InserirResidenciaRequest request);
        
        // CODEGEN: Generating message contract since element name ConsultarTodosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarTodos", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.ConsultarTodosResponse ConsultarTodos(HomeAutomex.HomeAutomexService.ConsultarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsultarTodosResponse> ConsultarTodosAsync(HomeAutomex.HomeAutomexService.ConsultarTodosRequest request);
        
        // CODEGEN: Generating message contract since element name jUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExistirUsuario", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.ExistirUsuarioResponse ExistirUsuario(HomeAutomex.HomeAutomexService.ExistirUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExistirUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExistirUsuarioResponse> ExistirUsuarioAsync(HomeAutomex.HomeAutomexService.ExistirUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirUsuárioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirUsuário", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody Body;
        
        public InserirUsuárioRequest() {
        }
        
        public InserirUsuárioRequest(HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirUsuárioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jUsuario;
        
        public InserirUsuárioRequestBody() {
        }
        
        public InserirUsuárioRequestBody(string jUsuario) {
            this.jUsuario = jUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirUsuárioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirUsuárioResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirUsuárioResponseBody Body;
        
        public InserirUsuárioResponse() {
        }
        
        public InserirUsuárioResponse(HomeAutomex.HomeAutomexService.InserirUsuárioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirUsuárioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InserirUsuárioResult;
        
        public InserirUsuárioResponseBody() {
        }
        
        public InserirUsuárioResponseBody(string InserirUsuárioResult) {
            this.InserirUsuárioResult = InserirUsuárioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirResidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirResidencia", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirResidenciaRequestBody Body;
        
        public InserirResidenciaRequest() {
        }
        
        public InserirResidenciaRequest(HomeAutomex.HomeAutomexService.InserirResidenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirResidenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jResidencia;
        
        public InserirResidenciaRequestBody() {
        }
        
        public InserirResidenciaRequestBody(string jResidencia) {
            this.jResidencia = jResidencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirResidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirResidenciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirResidenciaResponseBody Body;
        
        public InserirResidenciaResponse() {
        }
        
        public InserirResidenciaResponse(HomeAutomex.HomeAutomexService.InserirResidenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirResidenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InserirResidenciaResult;
        
        public InserirResidenciaResponseBody() {
        }
        
        public InserirResidenciaResponseBody(string InserirResidenciaResult) {
            this.InserirResidenciaResult = InserirResidenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarTodosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarTodos", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ConsultarTodosRequestBody Body;
        
        public ConsultarTodosRequest() {
        }
        
        public ConsultarTodosRequest(HomeAutomex.HomeAutomexService.ConsultarTodosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarTodosRequestBody {
        
        public ConsultarTodosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarTodosResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ConsultarTodosResponseBody Body;
        
        public ConsultarTodosResponse() {
        }
        
        public ConsultarTodosResponse(HomeAutomex.HomeAutomexService.ConsultarTodosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarTodosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarTodosResult;
        
        public ConsultarTodosResponseBody() {
        }
        
        public ConsultarTodosResponseBody(string ConsultarTodosResult) {
            this.ConsultarTodosResult = ConsultarTodosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistirUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistirUsuario", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ExistirUsuarioRequestBody Body;
        
        public ExistirUsuarioRequest() {
        }
        
        public ExistirUsuarioRequest(HomeAutomex.HomeAutomexService.ExistirUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExistirUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jUsuario;
        
        public ExistirUsuarioRequestBody() {
        }
        
        public ExistirUsuarioRequestBody(string jUsuario) {
            this.jUsuario = jUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistirUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistirUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ExistirUsuarioResponseBody Body;
        
        public ExistirUsuarioResponse() {
        }
        
        public ExistirUsuarioResponse(HomeAutomex.HomeAutomexService.ExistirUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExistirUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExistirUsuarioResult;
        
        public ExistirUsuarioResponseBody() {
        }
        
        public ExistirUsuarioResponseBody(string ExistirUsuarioResult) {
            this.ExistirUsuarioResult = ExistirUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HomeAutomexWSSoapChannel : HomeAutomex.HomeAutomexService.HomeAutomexWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HomeAutomexWSSoapClient : System.ServiceModel.ClientBase<HomeAutomex.HomeAutomexService.HomeAutomexWSSoap>, HomeAutomex.HomeAutomexService.HomeAutomexWSSoap {
        
        public HomeAutomexWSSoapClient() {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeAutomexWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.InserirUsuárioResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirUsuário(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request) {
            return base.Channel.InserirUsuário(request);
        }
        
        public string InserirUsuário(string jUsuario) {
            HomeAutomex.HomeAutomexService.InserirUsuárioRequest inValue = new HomeAutomex.HomeAutomexService.InserirUsuárioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            HomeAutomex.HomeAutomexService.InserirUsuárioResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirUsuário(inValue);
            return retVal.Body.InserirUsuárioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirUsuárioAsync(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request) {
            return base.Channel.InserirUsuárioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> InserirUsuárioAsync(string jUsuario) {
            HomeAutomex.HomeAutomexService.InserirUsuárioRequest inValue = new HomeAutomex.HomeAutomexService.InserirUsuárioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirUsuárioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.InserirResidenciaResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirResidencia(HomeAutomex.HomeAutomexService.InserirResidenciaRequest request) {
            return base.Channel.InserirResidencia(request);
        }
        
        public string InserirResidencia(string jResidencia) {
            HomeAutomex.HomeAutomexService.InserirResidenciaRequest inValue = new HomeAutomex.HomeAutomexService.InserirResidenciaRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirResidenciaRequestBody();
            inValue.Body.jResidencia = jResidencia;
            HomeAutomex.HomeAutomexService.InserirResidenciaResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirResidencia(inValue);
            return retVal.Body.InserirResidenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirResidenciaResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirResidenciaAsync(HomeAutomex.HomeAutomexService.InserirResidenciaRequest request) {
            return base.Channel.InserirResidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirResidenciaResponse> InserirResidenciaAsync(string jResidencia) {
            HomeAutomex.HomeAutomexService.InserirResidenciaRequest inValue = new HomeAutomex.HomeAutomexService.InserirResidenciaRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirResidenciaRequestBody();
            inValue.Body.jResidencia = jResidencia;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirResidenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.ConsultarTodosResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ConsultarTodos(HomeAutomex.HomeAutomexService.ConsultarTodosRequest request) {
            return base.Channel.ConsultarTodos(request);
        }
        
        public string ConsultarTodos() {
            HomeAutomex.HomeAutomexService.ConsultarTodosRequest inValue = new HomeAutomex.HomeAutomexService.ConsultarTodosRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ConsultarTodosRequestBody();
            HomeAutomex.HomeAutomexService.ConsultarTodosResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ConsultarTodos(inValue);
            return retVal.Body.ConsultarTodosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsultarTodosResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ConsultarTodosAsync(HomeAutomex.HomeAutomexService.ConsultarTodosRequest request) {
            return base.Channel.ConsultarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsultarTodosResponse> ConsultarTodosAsync() {
            HomeAutomex.HomeAutomexService.ConsultarTodosRequest inValue = new HomeAutomex.HomeAutomexService.ConsultarTodosRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ConsultarTodosRequestBody();
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ConsultarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.ExistirUsuarioResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ExistirUsuario(HomeAutomex.HomeAutomexService.ExistirUsuarioRequest request) {
            return base.Channel.ExistirUsuario(request);
        }
        
        public string ExistirUsuario(string jUsuario) {
            HomeAutomex.HomeAutomexService.ExistirUsuarioRequest inValue = new HomeAutomex.HomeAutomexService.ExistirUsuarioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ExistirUsuarioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            HomeAutomex.HomeAutomexService.ExistirUsuarioResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ExistirUsuario(inValue);
            return retVal.Body.ExistirUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExistirUsuarioResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ExistirUsuarioAsync(HomeAutomex.HomeAutomexService.ExistirUsuarioRequest request) {
            return base.Channel.ExistirUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExistirUsuarioResponse> ExistirUsuarioAsync(string jUsuario) {
            HomeAutomex.HomeAutomexService.ExistirUsuarioRequest inValue = new HomeAutomex.HomeAutomexService.ExistirUsuarioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ExistirUsuarioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ExistirUsuarioAsync(inValue);
        }
    }
}
