//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAutomex.HomeAutomexService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HomeAutomexService.HomeAutomexWSSoap")]
    public interface HomeAutomexWSSoap {
        
        // CODEGEN: Generating message contract since element name jUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirUsuário", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.InserirUsuárioResponse InserirUsuário(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirUsuário", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> InserirUsuárioAsync(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request);
        
        // CODEGEN: Generating message contract since element name jUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterarUsuario", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.AlterarUsuarioResponse AlterarUsuario(HomeAutomex.HomeAutomexService.AlterarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.AlterarUsuarioResponse> AlterarUsuarioAsync(HomeAutomex.HomeAutomexService.AlterarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name jChave from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuarioPorChave", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveResponse BuscarUsuarioPorChave(HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuarioPorChave", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveResponse> BuscarUsuarioPorChaveAsync(HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequest request);
        
        // CODEGEN: Generating message contract since element name jChave from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirUsuario", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.ExcluirUsuarioResponse ExcluirUsuario(HomeAutomex.HomeAutomexService.ExcluirUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcluirUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExcluirUsuarioResponse> ExcluirUsuarioAsync(HomeAutomex.HomeAutomexService.ExcluirUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name ConsutarTodosUsuariosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsutarTodosUsuarios", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosResponse ConsutarTodosUsuarios(HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsutarTodosUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosResponse> ConsutarTodosUsuariosAsync(HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequest request);
        
        // CODEGEN: Generating message contract since element name jUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExistirUsuario", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.ExistirUsuarioResponse ExistirUsuario(HomeAutomex.HomeAutomexService.ExistirUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExistirUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExistirUsuarioResponse> ExistirUsuarioAsync(HomeAutomex.HomeAutomexService.ExistirUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name jResidencia from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirResidencia", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.InserirResidenciaResponse InserirResidencia(HomeAutomex.HomeAutomexService.InserirResidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirResidencia", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirResidenciaResponse> InserirResidenciaAsync(HomeAutomex.HomeAutomexService.InserirResidenciaRequest request);
        
        // CODEGEN: Generating message contract since element name ConsutarTodosResideciaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsutarTodosResidecia", ReplyAction="*")]
        HomeAutomex.HomeAutomexService.ConsutarTodosResideciaResponse ConsutarTodosResidecia(HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsutarTodosResidecia", ReplyAction="*")]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsutarTodosResideciaResponse> ConsutarTodosResideciaAsync(HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirUsuárioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirUsuário", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody Body;
        
        public InserirUsuárioRequest() {
        }
        
        public InserirUsuárioRequest(HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirUsuárioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jUsuario;
        
        public InserirUsuárioRequestBody() {
        }
        
        public InserirUsuárioRequestBody(string jUsuario) {
            this.jUsuario = jUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirUsuárioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirUsuárioResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirUsuárioResponseBody Body;
        
        public InserirUsuárioResponse() {
        }
        
        public InserirUsuárioResponse(HomeAutomex.HomeAutomexService.InserirUsuárioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirUsuárioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InserirUsuárioResult;
        
        public InserirUsuárioResponseBody() {
        }
        
        public InserirUsuárioResponseBody(string InserirUsuárioResult) {
            this.InserirUsuárioResult = InserirUsuárioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlterarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.AlterarUsuarioRequestBody Body;
        
        public AlterarUsuarioRequest() {
        }
        
        public AlterarUsuarioRequest(HomeAutomex.HomeAutomexService.AlterarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jUsuario;
        
        public AlterarUsuarioRequestBody() {
        }
        
        public AlterarUsuarioRequestBody(string jUsuario) {
            this.jUsuario = jUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlterarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.AlterarUsuarioResponseBody Body;
        
        public AlterarUsuarioResponse() {
        }
        
        public AlterarUsuarioResponse(HomeAutomex.HomeAutomexService.AlterarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AlterarUsuarioResult;
        
        public AlterarUsuarioResponseBody() {
        }
        
        public AlterarUsuarioResponseBody(string AlterarUsuarioResult) {
            this.AlterarUsuarioResult = AlterarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarUsuarioPorChaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarUsuarioPorChave", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequestBody Body;
        
        public BuscarUsuarioPorChaveRequest() {
        }
        
        public BuscarUsuarioPorChaveRequest(HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarUsuarioPorChaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jChave;
        
        public BuscarUsuarioPorChaveRequestBody() {
        }
        
        public BuscarUsuarioPorChaveRequestBody(string jChave) {
            this.jChave = jChave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarUsuarioPorChaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarUsuarioPorChaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveResponseBody Body;
        
        public BuscarUsuarioPorChaveResponse() {
        }
        
        public BuscarUsuarioPorChaveResponse(HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarUsuarioPorChaveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarUsuarioPorChaveResult;
        
        public BuscarUsuarioPorChaveResponseBody() {
        }
        
        public BuscarUsuarioPorChaveResponseBody(string BuscarUsuarioPorChaveResult) {
            this.BuscarUsuarioPorChaveResult = BuscarUsuarioPorChaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirUsuario", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ExcluirUsuarioRequestBody Body;
        
        public ExcluirUsuarioRequest() {
        }
        
        public ExcluirUsuarioRequest(HomeAutomex.HomeAutomexService.ExcluirUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcluirUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jChave;
        
        public ExcluirUsuarioRequestBody() {
        }
        
        public ExcluirUsuarioRequestBody(string jChave) {
            this.jChave = jChave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcluirUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcluirUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ExcluirUsuarioResponseBody Body;
        
        public ExcluirUsuarioResponse() {
        }
        
        public ExcluirUsuarioResponse(HomeAutomex.HomeAutomexService.ExcluirUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcluirUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExcluirUsuarioResult;
        
        public ExcluirUsuarioResponseBody() {
        }
        
        public ExcluirUsuarioResponseBody(string ExcluirUsuarioResult) {
            this.ExcluirUsuarioResult = ExcluirUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsutarTodosUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsutarTodosUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequestBody Body;
        
        public ConsutarTodosUsuariosRequest() {
        }
        
        public ConsutarTodosUsuariosRequest(HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsutarTodosUsuariosRequestBody {
        
        public ConsutarTodosUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsutarTodosUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsutarTodosUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosResponseBody Body;
        
        public ConsutarTodosUsuariosResponse() {
        }
        
        public ConsutarTodosUsuariosResponse(HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsutarTodosUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsutarTodosUsuariosResult;
        
        public ConsutarTodosUsuariosResponseBody() {
        }
        
        public ConsutarTodosUsuariosResponseBody(string ConsutarTodosUsuariosResult) {
            this.ConsutarTodosUsuariosResult = ConsutarTodosUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistirUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistirUsuario", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ExistirUsuarioRequestBody Body;
        
        public ExistirUsuarioRequest() {
        }
        
        public ExistirUsuarioRequest(HomeAutomex.HomeAutomexService.ExistirUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExistirUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jUsuario;
        
        public ExistirUsuarioRequestBody() {
        }
        
        public ExistirUsuarioRequestBody(string jUsuario) {
            this.jUsuario = jUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistirUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistirUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ExistirUsuarioResponseBody Body;
        
        public ExistirUsuarioResponse() {
        }
        
        public ExistirUsuarioResponse(HomeAutomex.HomeAutomexService.ExistirUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExistirUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExistirUsuarioResult;
        
        public ExistirUsuarioResponseBody() {
        }
        
        public ExistirUsuarioResponseBody(string ExistirUsuarioResult) {
            this.ExistirUsuarioResult = ExistirUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirResidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirResidencia", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirResidenciaRequestBody Body;
        
        public InserirResidenciaRequest() {
        }
        
        public InserirResidenciaRequest(HomeAutomex.HomeAutomexService.InserirResidenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirResidenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jResidencia;
        
        public InserirResidenciaRequestBody() {
        }
        
        public InserirResidenciaRequestBody(string jResidencia) {
            this.jResidencia = jResidencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirResidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirResidenciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.InserirResidenciaResponseBody Body;
        
        public InserirResidenciaResponse() {
        }
        
        public InserirResidenciaResponse(HomeAutomex.HomeAutomexService.InserirResidenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirResidenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InserirResidenciaResult;
        
        public InserirResidenciaResponseBody() {
        }
        
        public InserirResidenciaResponseBody(string InserirResidenciaResult) {
            this.InserirResidenciaResult = InserirResidenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsutarTodosResideciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsutarTodosResidecia", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequestBody Body;
        
        public ConsutarTodosResideciaRequest() {
        }
        
        public ConsutarTodosResideciaRequest(HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsutarTodosResideciaRequestBody {
        
        public ConsutarTodosResideciaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsutarTodosResideciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsutarTodosResideciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public HomeAutomex.HomeAutomexService.ConsutarTodosResideciaResponseBody Body;
        
        public ConsutarTodosResideciaResponse() {
        }
        
        public ConsutarTodosResideciaResponse(HomeAutomex.HomeAutomexService.ConsutarTodosResideciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsutarTodosResideciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsutarTodosResideciaResult;
        
        public ConsutarTodosResideciaResponseBody() {
        }
        
        public ConsutarTodosResideciaResponseBody(string ConsutarTodosResideciaResult) {
            this.ConsutarTodosResideciaResult = ConsutarTodosResideciaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HomeAutomexWSSoapChannel : HomeAutomex.HomeAutomexService.HomeAutomexWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HomeAutomexWSSoapClient : System.ServiceModel.ClientBase<HomeAutomex.HomeAutomexService.HomeAutomexWSSoap>, HomeAutomex.HomeAutomexService.HomeAutomexWSSoap {
        
        public HomeAutomexWSSoapClient() {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeAutomexWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeAutomexWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.InserirUsuárioResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirUsuário(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request) {
            return base.Channel.InserirUsuário(request);
        }
        
        public string InserirUsuário(string jUsuario) {
            HomeAutomex.HomeAutomexService.InserirUsuárioRequest inValue = new HomeAutomex.HomeAutomexService.InserirUsuárioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            HomeAutomex.HomeAutomexService.InserirUsuárioResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirUsuário(inValue);
            return retVal.Body.InserirUsuárioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirUsuárioAsync(HomeAutomex.HomeAutomexService.InserirUsuárioRequest request) {
            return base.Channel.InserirUsuárioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirUsuárioResponse> InserirUsuárioAsync(string jUsuario) {
            HomeAutomex.HomeAutomexService.InserirUsuárioRequest inValue = new HomeAutomex.HomeAutomexService.InserirUsuárioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirUsuárioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirUsuárioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.AlterarUsuarioResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.AlterarUsuario(HomeAutomex.HomeAutomexService.AlterarUsuarioRequest request) {
            return base.Channel.AlterarUsuario(request);
        }
        
        public string AlterarUsuario(string jUsuario) {
            HomeAutomex.HomeAutomexService.AlterarUsuarioRequest inValue = new HomeAutomex.HomeAutomexService.AlterarUsuarioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.AlterarUsuarioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            HomeAutomex.HomeAutomexService.AlterarUsuarioResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).AlterarUsuario(inValue);
            return retVal.Body.AlterarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.AlterarUsuarioResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.AlterarUsuarioAsync(HomeAutomex.HomeAutomexService.AlterarUsuarioRequest request) {
            return base.Channel.AlterarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.AlterarUsuarioResponse> AlterarUsuarioAsync(string jUsuario) {
            HomeAutomex.HomeAutomexService.AlterarUsuarioRequest inValue = new HomeAutomex.HomeAutomexService.AlterarUsuarioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.AlterarUsuarioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).AlterarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.BuscarUsuarioPorChave(HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequest request) {
            return base.Channel.BuscarUsuarioPorChave(request);
        }
        
        public string BuscarUsuarioPorChave(string jChave) {
            HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequest inValue = new HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequestBody();
            inValue.Body.jChave = jChave;
            HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).BuscarUsuarioPorChave(inValue);
            return retVal.Body.BuscarUsuarioPorChaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.BuscarUsuarioPorChaveAsync(HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequest request) {
            return base.Channel.BuscarUsuarioPorChaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveResponse> BuscarUsuarioPorChaveAsync(string jChave) {
            HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequest inValue = new HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.BuscarUsuarioPorChaveRequestBody();
            inValue.Body.jChave = jChave;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).BuscarUsuarioPorChaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.ExcluirUsuarioResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ExcluirUsuario(HomeAutomex.HomeAutomexService.ExcluirUsuarioRequest request) {
            return base.Channel.ExcluirUsuario(request);
        }
        
        public string ExcluirUsuario(string jChave) {
            HomeAutomex.HomeAutomexService.ExcluirUsuarioRequest inValue = new HomeAutomex.HomeAutomexService.ExcluirUsuarioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ExcluirUsuarioRequestBody();
            inValue.Body.jChave = jChave;
            HomeAutomex.HomeAutomexService.ExcluirUsuarioResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ExcluirUsuario(inValue);
            return retVal.Body.ExcluirUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExcluirUsuarioResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ExcluirUsuarioAsync(HomeAutomex.HomeAutomexService.ExcluirUsuarioRequest request) {
            return base.Channel.ExcluirUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExcluirUsuarioResponse> ExcluirUsuarioAsync(string jChave) {
            HomeAutomex.HomeAutomexService.ExcluirUsuarioRequest inValue = new HomeAutomex.HomeAutomexService.ExcluirUsuarioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ExcluirUsuarioRequestBody();
            inValue.Body.jChave = jChave;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ExcluirUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ConsutarTodosUsuarios(HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequest request) {
            return base.Channel.ConsutarTodosUsuarios(request);
        }
        
        public string ConsutarTodosUsuarios() {
            HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequest inValue = new HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequestBody();
            HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ConsutarTodosUsuarios(inValue);
            return retVal.Body.ConsutarTodosUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ConsutarTodosUsuariosAsync(HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequest request) {
            return base.Channel.ConsutarTodosUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosResponse> ConsutarTodosUsuariosAsync() {
            HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequest inValue = new HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ConsutarTodosUsuariosRequestBody();
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ConsutarTodosUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.ExistirUsuarioResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ExistirUsuario(HomeAutomex.HomeAutomexService.ExistirUsuarioRequest request) {
            return base.Channel.ExistirUsuario(request);
        }
        
        public string ExistirUsuario(string jUsuario) {
            HomeAutomex.HomeAutomexService.ExistirUsuarioRequest inValue = new HomeAutomex.HomeAutomexService.ExistirUsuarioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ExistirUsuarioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            HomeAutomex.HomeAutomexService.ExistirUsuarioResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ExistirUsuario(inValue);
            return retVal.Body.ExistirUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExistirUsuarioResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ExistirUsuarioAsync(HomeAutomex.HomeAutomexService.ExistirUsuarioRequest request) {
            return base.Channel.ExistirUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ExistirUsuarioResponse> ExistirUsuarioAsync(string jUsuario) {
            HomeAutomex.HomeAutomexService.ExistirUsuarioRequest inValue = new HomeAutomex.HomeAutomexService.ExistirUsuarioRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ExistirUsuarioRequestBody();
            inValue.Body.jUsuario = jUsuario;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ExistirUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.InserirResidenciaResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirResidencia(HomeAutomex.HomeAutomexService.InserirResidenciaRequest request) {
            return base.Channel.InserirResidencia(request);
        }
        
        public string InserirResidencia(string jResidencia) {
            HomeAutomex.HomeAutomexService.InserirResidenciaRequest inValue = new HomeAutomex.HomeAutomexService.InserirResidenciaRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirResidenciaRequestBody();
            inValue.Body.jResidencia = jResidencia;
            HomeAutomex.HomeAutomexService.InserirResidenciaResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirResidencia(inValue);
            return retVal.Body.InserirResidenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirResidenciaResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.InserirResidenciaAsync(HomeAutomex.HomeAutomexService.InserirResidenciaRequest request) {
            return base.Channel.InserirResidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.InserirResidenciaResponse> InserirResidenciaAsync(string jResidencia) {
            HomeAutomex.HomeAutomexService.InserirResidenciaRequest inValue = new HomeAutomex.HomeAutomexService.InserirResidenciaRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.InserirResidenciaRequestBody();
            inValue.Body.jResidencia = jResidencia;
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).InserirResidenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HomeAutomex.HomeAutomexService.ConsutarTodosResideciaResponse HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ConsutarTodosResidecia(HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequest request) {
            return base.Channel.ConsutarTodosResidecia(request);
        }
        
        public string ConsutarTodosResidecia() {
            HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequest inValue = new HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequestBody();
            HomeAutomex.HomeAutomexService.ConsutarTodosResideciaResponse retVal = ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ConsutarTodosResidecia(inValue);
            return retVal.Body.ConsutarTodosResideciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsutarTodosResideciaResponse> HomeAutomex.HomeAutomexService.HomeAutomexWSSoap.ConsutarTodosResideciaAsync(HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequest request) {
            return base.Channel.ConsutarTodosResideciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<HomeAutomex.HomeAutomexService.ConsutarTodosResideciaResponse> ConsutarTodosResideciaAsync() {
            HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequest inValue = new HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequest();
            inValue.Body = new HomeAutomex.HomeAutomexService.ConsutarTodosResideciaRequestBody();
            return ((HomeAutomex.HomeAutomexService.HomeAutomexWSSoap)(this)).ConsutarTodosResideciaAsync(inValue);
        }
    }
}
